-- Example: tracking data citations FROM and TO a funder's papers (here: NIH, GRID grid.94365.3d,
-- including all child institutes via the organization hierarchy).
--
-- Demonstrates the two flagship joins on the data_citations view:
--   FROM: what data a funder's papers generate (Primary) and reuse (Secondary)
--   TO:   Primary pairs define the funder's GENERATED datasets; Secondary citations of those
--         datasets by other papers measure reuse — split by whether the reusing paper is
--         itself funder-supported (internal) or not (external spillover).
--
-- Requires in tables.yaml: work_dataset, publications_metadata (with funder_orgs + id/year),
-- organizations_metadata (with organization_recursive_child_ids).
-- Swap the GRID id to profile any funder; add family_or_repo / year grouping for trends.

-- Data citations FROM and TO NIH-funded papers
WITH nih_pubs AS (   -- Simon's base query: NIH (grid.94365.3d) incl. all child institutes
  SELECT DISTINCT p.id, p.year
  FROM `${publications_metadata}` p,
       UNNEST(funder_orgs) fo
  INNER JOIN `${organizations_metadata}` o
    ON o.id = 'grid.94365.3d'
   AND (fo = o.id OR fo IN UNNEST(o.organization_recursive_child_ids))
),
-- Direction 1: FROM — data citations made by NIH-funded papers
from_nih AS (
  SELECT v.type, v.id_kind, COUNT(*) n, COUNT(DISTINCT v.publication_id) papers
  FROM `${work_dataset}.data_citations` v
  JOIN nih_pubs ON nih_pubs.id = v.publication_id
  WHERE v.type IN ('Primary','Secondary') AND v.is_data_type
  GROUP BY 1, 2
),
-- Direction 2: TO — datasets GENERATED by NIH-funded papers...
nih_generated AS (
  SELECT DISTINCT v.dataset_id, v.id_kind, v.publication_id AS generating_pub
  FROM `${work_dataset}.data_citations` v
  JOIN nih_pubs ON nih_pubs.id = v.publication_id
  WHERE v.type = 'Primary' AND v.is_data_type
),
-- ...and every reuse of those datasets by OTHER papers
reuse_of_nih_data AS (
  SELECT g.id_kind,
         COUNT(*) reuse_citations,
         COUNT(DISTINCT v.dataset_id) datasets_reused,
         COUNT(DISTINCT v.publication_id) reusing_papers,
         COUNTIF(nih2.id IS NOT NULL) reuse_by_nih_funded,
         COUNTIF(nih2.id IS NULL) reuse_by_external
  FROM `${work_dataset}.data_citations` v
  JOIN nih_generated g ON g.dataset_id = v.dataset_id AND g.id_kind = v.id_kind
  LEFT JOIN nih_pubs nih2 ON nih2.id = v.publication_id
  WHERE v.type = 'Secondary' AND v.publication_id != g.generating_pub
  GROUP BY 1
)
SELECT 'FROM: NIH papers citing data' AS direction,
       CONCAT(id_kind, ' / ', type) AS slice,
       n AS citations, papers AS distinct_papers,
       NULL AS datasets_reused, NULL AS by_nih, NULL AS by_external
FROM from_nih
UNION ALL
SELECT 'TO: reuse of NIH-generated data', id_kind,
       reuse_citations, reusing_papers, datasets_reused, reuse_by_nih_funded, reuse_by_external
FROM reuse_of_nih_data
ORDER BY direction, slice