-- SRAD registries: what every rule, accession pattern, cue and classifying method actually is.
-- Satisfies SRAD_DESIGN.md requirements 2 (inspect the regex for each rule and parser) and
-- 5 (expose the model used).
--
-- `rules` and `methods` are hand-authored literals rather than derived, because the thing being
-- published is the DEFINITION of each rule and the provenance of each method, and neither exists
-- as data anywhere in the pipeline -- they exist as SQL and as measurements recorded in commit
-- messages and docs. Encoding them here is deliberate: it makes the definitions queryable, and
-- it makes them fail loudly when a rule changes and this table is not updated.
--
-- `measured_precision` is NULL wherever a rule has never been measured on the population it
-- actually decides. That is not laziness. Borrowing a precision figure from a different
-- population is the specific error that produced two wrong conclusions in this project (an
-- 84.5%-vs-1.1% "divergence" that was a selection artefact, and a residue base-rate estimate of
-- 10-14% where direct labelling measured 50%), so a NULL here is a stronger statement than a
-- number.

CREATE OR REPLACE TABLE `${srad_dataset}.rules` AS
SELECT * FROM UNNEST([
  STRUCT<rule_id STRING, tier STRING, stage STRING, decision STRING, definition_kind STRING,
         definition STRING, measured_precision FLOAT64, measured_on STRING, n_labels INT64,
         notes STRING>

  -- ---------- DOI arm: registered relations ----------
  ('supplement_to', 'registered_relation', '61', 'Primary', 'predicate',
   'is_supplement_to_article', 1.000, 'kaggle+rdmpage gold, 2026-09-04', 42,
   'DataCite asserts IsSupplementTo this exact article. The repository is the authority, so no text is read. 42/42 correct on gold.'),

  -- ---------- DOI arm: metadata similarity ----------
  ('metadata_match', 'metadata_similarity', '61', 'Primary', 'predicate',
   'author_overlap_frac_exact >= 0.4 OR (author_overlap_exact >= 2 AND title_jaccard >= 0.3) OR title_jaccard >= 0.6 OR author_overlap_frac >= 1.0',
   0.920, 'kaggle+rdmpage gold, 2026-09-04', 163,
   'The first three arms use EXACT creator-name matching. The fourth uses token matching for multi-token DataCite creator strings and fires only at a complete match: measured 0.838 (n=68) at frac=1.0 versus 0.60 for partial matches, so partial token overlap is deliberately not promoted.'),
  ('metadata_match_not_first', 'metadata_similarity', '65', 'Secondary', 'predicate',
   'metadata_match Primary AND NOT earliest citing paper for this dataset (ties broken by similarity, then publication_id); rows sharing the earliest paper\'s normalised title ride along',
   NULL, NULL, NULL,
   'One-Primary-per-dataset demotion. A dataset has one generating paper; same-group follow-ups reusing their own data are Secondary. Never measured directly on the demoted population.'),
  ('popular_dataset', 'metadata_similarity', '61', 'Secondary', 'predicate',
   'n_citing_articles >= 5', 0.939, 'kaggle+rdmpage gold, 2026-09-04', 49,
   'Reuse-count argument: a dataset cited by five papers was not generated by the fifth. Unavailable where n_citing_articles = 1, which is the native state of a primary deposit.'),
  ('multi_cited_not_first', 'metadata_similarity', '61', 'Secondary', 'predicate',
   'n_citing_articles BETWEEN 2 AND 4 AND citing_rank > 1', 0.750, 'kaggle+rdmpage gold, 2026-09-04', 8,
   'Same reuse-count logic at low counts. n=8 on gold, so the precision figure is indicative only.'),

  -- ---------- DOI arm: LLM tier ----------
  ('llm_primary', 'llm', '71', 'Primary', 'llm_verdict',
   'cached PRIMARY verdict from method srad.methods.llm_doi_primary_v3, applied only to rows still Unclassified and only where the dataset has no Primary from a stronger rule',
   0.937, 'human labels drawn from the DOI residue, 2026-09-04', 63,
   'Only the PRIMARY verdict is applied. The same method\'s SECONDARY verdict measured 0.560 and is never written: explicit self-referential wording is positive evidence of primary deposit, but its absence is not evidence of reuse.'),

  -- ---------- DOI arm: undecided, partitioned by mention location ----------
  ('residual_availability_only', 'none', '61', 'Unclassified', 'predicate',
   'in_availability AND NOT via_reference', NULL, NULL, NULL,
   'Undecided. Mentioned in a data-availability statement and not via a reference. The most Primary-rich residual stratum (37.5% by LLM verdict).'),
  ('residual_availability_ref', 'none', '61', 'Unclassified', 'predicate',
   'in_availability AND via_reference', NULL, NULL, NULL, 'Undecided.'),
  ('residual_reference_only', 'none', '61', 'Unclassified', 'predicate',
   'via_reference AND NOT in_availability', NULL, NULL, NULL,
   'Undecided. 78% of the residue but only 2.5% Primary by LLM verdict, so deliberately left unscored by the LLM tier on cost grounds.'),
  ('residual_no_location_signal', 'none', '61', 'Unclassified', 'predicate',
   'NOT in_availability AND NOT via_reference', NULL, NULL, NULL, 'Undecided.'),

  -- ---------- Accession arm: format validation and family priors ----------
  ('regex_invalid', 'family_prior', '62', 'Excluded', 'regex',
   'accession fails its family pattern in srad.accession_patterns', NULL, NULL, NULL,
   'Excluded from the product entirely. A too-narrow pattern fails silently here, since a non-matching accession is indistinguishable from one never text-mined.'),
  ('band_notation', 'family_prior', '62', 'Excluded', 'regex',
   'pdb family; id matches ^[0-9][pq][0-9]{2}$ case-sensitively; no mention of the pair contains "pdb" or "protein data bank"',
   0.873, 'pdb pairs the rule excludes, sampled 2026-09-25 (lower bound: 7 bare table cells counted as errors)', 55,
   'Chromosome bands (7q22.1, chromosome 8p11) are real PDB ids too, so only the text can tell them apart. 48 of 55 sampled exclusions were confirmed non-data, 0 were structures. Judged by Claude from context, not hand-labelled. Gold contains no band-shaped ids.'),
  ('glycan_notation', 'family_prior', '62', 'Excluded', 'regex',
   'pdb family; id matches ^[0-9](Fuc|Gal|Glc|Man|Xyl|Neu|Sia|Rha|Ara|Hex|Kdo)$ case-sensitively; pair has at least one mention',
   1.0, 'pdb pairs the rule excludes, sampled 2026-09-25', 45,
   'Monosaccharide residues in glycan linkage notation (Galα1-3Gal). 45 of 45 sampled were glycan notation, including every pair with a PDB cue. Judged by Claude from context, not hand-labelled.'),
  ('reference_db_prior', 'family_prior', '62', 'Secondary', 'predicate',
   'family default_type_prior = \'Secondary\' (reference databases: UniProt, RefSeq, Ensembl, Pfam, InterPro, Cellosaurus, HPA)',
   NULL, NULL, NULL,
   'Citing a reference database is reuse almost by definition -- you do not deposit into UniProt. Applied as a prior, not from evidence.'),
  ('kaggle_samn_rule', 'family_prior', '62', 'Primary', 'predicate',
   'family = \'biosample\' AND competition-validated SAMN rule', NULL, NULL, NULL,
   'Inherited from the Make Data Count Kaggle winners.'),
  ('kaggle_emdb_rule', 'family_prior', '62', 'Primary', 'predicate',
   'family = \'emdb\\', NULL, NULL, NULL,
   'Inherited from the competition. Carries the emdb family alone: it has no deposit records and no reference-DB prior.'),
  ('kaggle_samn_rule_not_first', 'family_prior', '65', 'Secondary', 'predicate',
   'kaggle_samn_rule Primary AND not the earliest citing paper', NULL, NULL, NULL, 'Uniqueness demotion.'),
  ('kaggle_emdb_rule_not_first', 'family_prior', '65', 'Secondary', 'predicate',
   'kaggle_emdb_rule Primary AND not the earliest citing paper', NULL, NULL, NULL, 'Uniqueness demotion.'),

  -- ---------- Accession arm: mention-context cues ----------
  ('cue_primary', 'mention_cue', '64', 'Primary', 'predicate',
   'weighted cue score over srad.cue_lexicon matches in the mention sentences exceeds the deposition threshold',
   NULL, NULL, NULL,
   'Reads deposition language ("sequences were deposited under"). Applied only over rows left Unclassified by the tiers above.'),
  ('cue_secondary', 'mention_cue', '64', 'Secondary', 'predicate',
   'weighted cue score over srad.cue_lexicon matches exceeds the reuse threshold', NULL, NULL, NULL,
   'Reads reuse language ("sequences were obtained from").'),
  ('cue_primary_not_first', 'mention_cue', '65', 'Secondary', 'predicate',
   'cue_primary Primary AND not the earliest citing paper', NULL, NULL, NULL, 'Uniqueness demotion.'),

  -- ---------- Accession arm: repository deposit evidence ----------
  ('repo_linked_pub_primary', 'repository_evidence', '67', 'Primary', 'predicate',
   'deposit record\'s linked publication IS this article', 0.970, '123 independently adjudicated cases, 2026-08', 123,
   'The strongest evidence in the pipeline: the repository itself attributes the deposit to this article. The 0.97 figure is the adjudicated accuracy of the tier as a whole, not of this rule alone.'),
  ('repo_linked_other_secondary', 'repository_evidence', '67', 'Secondary', 'predicate',
   'deposit record links a DIFFERENT publication AND submitters are present AND author overlap with this article = 0',
   NULL, NULL, NULL,
   'The submitters-present condition matters: without it, families whose records carry no submitter names would satisfy "overlap = 0" trivially and be misread as reuse.'),
  ('repo_deposit_precedes_secondary', 'repository_evidence', '67', 'Secondary', 'predicate',
   'deposit year < publication year - 1', NULL, NULL, NULL,
   'Data deposited well before the citing paper was not generated for it.'),
  ('repo_author_date_primary', 'repository_evidence', '67', 'Primary', 'predicate',
   'submitter/author name overlap >= 1 AND ABS(deposit year - publication year) <= 1', NULL, NULL, NULL,
   'Same people, same time window.'),
  ('repo_org_date_primary', 'repository_evidence', '67', 'Primary', 'predicate',
   'submitting organisation matches an author affiliation AND deposit within +/-1 year', NULL, NULL, NULL,
   'Organisational depositors (sequencing centres) where individual names are absent.'),
  ('repo_project_of_primary', 'repository_evidence', '67', 'Primary', 'predicate',
   'accession belongs to a BioProject already decided Primary for this article', NULL, NULL, NULL,
   'Project-level propagation.'),
  ('repo_author_date_primary_not_first', 'repository_evidence', '68', 'Secondary', 'predicate',
   'repo_author_date_primary AND not the earliest citing paper', NULL, NULL, NULL, 'Uniqueness demotion.'),
  ('repo_org_date_primary_not_first', 'repository_evidence', '68', 'Secondary', 'predicate',
   'repo_org_date_primary AND not the earliest citing paper', NULL, NULL, NULL, 'Uniqueness demotion.'),

  -- ---------- Accession arm: model tier ----------
  ('model_primary', 'model', '69', 'Primary', 'model_threshold',
   'p_primary >= 0.85 from method srad.methods.mdc_type_clf_v1, AND the family has repository-evidence training labels',
   0.935, 'held-out repository-evidence labels', NULL,
   'The family eligibility condition is a guard, not decoration: eight families have no deposit records and so contributed no training labels, and a Primary claim there is untestable -- all gold-checkable cases in those families were Secondary.'),
  ('model_secondary', 'model', '69', 'Secondary', 'model_threshold',
   'p_primary <= 0.10 from method srad.methods.mdc_type_clf_v1', 0.974, 'held-out repository-evidence labels', NULL,
   'Allowed in every family. Confirmed on the gold-checkable subset of the no-training-label families at 27/27, and by a population check: restoring these calls raised coverage AND agreement on both benchmarks.'),

  -- ---------- Undecided ----------
  ('residual', 'none', '62', 'Unclassified', 'predicate',
   'no rule above fired', NULL, NULL, NULL,
   'Honest silence. Roughly 10.8% of the product. Where a tier could not demonstrate 0.8 precision on the population it would decide, it ships Unclassified instead.')
]);


-- Accession parsers: the regex per family, with its false-positive risk. Requirement 2's parser
-- half. Derived from the pipeline's own lexicon so it cannot drift from what actually ran.
CREATE OR REPLACE TABLE `${srad_dataset}.accession_patterns` AS
SELECT
  family,
  pattern,
  fp_risk,
  default_type_prior,
  patterns_key,
  (fp_risk != 'low' OR pattern IS NULL) AS excluded_from_regex_discovery,
  CAST(NULL AS STRING) AS fp_notes
FROM `${work_dataset}.accession_families`;


-- Cue lexicon: the deposition/reuse phrases and their weights, exactly as scored.
CREATE OR REPLACE TABLE `${srad_dataset}.cue_lexicon` AS
SELECT cue_id, direction, pattern, weight
FROM `${work_dataset}.classification_cues`;


-- Methods: every component that classifies, with the provenance needed to reproduce it.
-- For the LLM the prompt IS the method -- two earlier prompts scored 0.317 and 0.303 against
-- gold where this one scored 0.782 overall and 0.937 on its applied verdict -- so the full text
-- is published rather than a description of it.
CREATE OR REPLACE TABLE `${srad_dataset}.methods` AS
SELECT * FROM UNNEST([
  STRUCT<method_id STRING, kind STRING, name STRING, version STRING, endpoint STRING,
         prompt_text STRING, training_population STRING, precision_by_class STRING,
         applies_to_families STRING, first_used_release STRING, notes STRING>

  ('mdc_type_clf_v1', 'bqml_classifier', 'BOOSTED_TREE_CLASSIFIER', 'v1 (trained 2026-08-14)',
   NULL, NULL,
   'Repository-evidence labels only -- never cue- or LLM-derived ones. Features restricted to what an undecided pair possesses (mention statistics and locations, cue score, family, article metadata patterns, citation-count structure) and deliberately exclude the metadata that generated the labels.',
   'Primary 0.935 at p>=0.85; Secondary 0.974 at p<=0.10; AUC 0.82',
   'Primary verdicts only in families with repository-evidence training labels; Secondary verdicts in all families',
   '202609',
   'Works through calibration and abstention rather than discrimination: the 0.10-0.85 band is left Unclassified on purpose. By feature gain, n_citing_articles and bare_id_share dominate and family ranks 14th, so it is not a family prior in disguise.'),

  ('llm_doi_primary_v3', 'llm', 'Gemini 2.5 Flash-Lite via BigQuery AI.GENERATE', 'prompt v3 (2026-09-04)',
   'gemini-2.5-flash-lite',
   '''Decide whether the article containing this sentence GENERATED the dataset (PRIMARY) or REUSED data that already existed (SECONDARY).

The repository does NOT tell you. Dryad, Zenodo, figshare, Dataverse and institutional archives hold both kinds of data. "Available from the Dryad Digital Repository" is not evidence of reuse. Ignore where the data sits and ask only WHOSE data it is.

PRIMARY -- the sentence refers to the data as belonging to this piece of work. Self-referential wording is the signal: "the data supporting the findings of this study", "data underpinning the analysis reported in this paper", "our data", "data generated in this work", "we deposited", "data for the compounds described here". Authors almost never write "we generated this" -- they write "the data for this paper are available at X". Treat that as PRIMARY.
Also PRIMARY: a dataset title of the form "Data from: <title>" where that title matches or closely echoes the article title. That is the standard convention for a dataset deposited alongside its own paper.

SECONDARY -- the data is attributed to someone else or to a resource that existed before this work: "obtained from", "downloaded from", "we used data from [another study/group]", "provided by", or an established ongoing resource (a satellite mission, reference database, national survey, long-running consortium) that the article clearly did not create. Also SECONDARY when the dataset is cited the way a piece of literature is cited, in support of a claim about prior work.

UNCLEAR -- a bare identifier or URL with no surrounding wording, or prose that does not indicate ownership either way.
NOT_DATA -- the identifier is not a research dataset (software, a paper, a reagent catalogue number).

Reply with exactly one word: PRIMARY, SECONDARY, NOT_DATA or UNCLEAR.''',
   'Zero-shot. No training. Inputs are the article title, dataset title, mention location and the mention sentence.',
   'PRIMARY 0.937 (95% CI 0.85-0.98, n=63); SECONDARY 0.560 and NEVER APPLIED; UNCLEAR not applied',
   'Dataset-DOI citations only. Scored on the availability_only, availability_ref and no_location_signal strata; reference_only left unscored on cost grounds.',
   '202609',
   'Applied asymmetrically on purpose. Two earlier prompts collapsed to near-constant SECONDARY predictors (0.317 and 0.303 against gold) by forbidding inference from field conventions and by treating "available from" a named archive as reuse -- which mislabels the commonest PRIMARY phrasing. The working version separates whose data it is from where it sits.'),

  ('rule_cascade', 'rule_cascade', 'Templated rule cascade', 'see srad.rules and releases.pipeline_commit',
   NULL, NULL,
   'Not fitted. Thresholds were chosen against competition-validated recipes and adjusted only where measured.',
   'Per rule -- see srad.rules.measured_precision', 'All', '202609',
   'The base tier. Carries the majority of decisions and is the reason the machine-learning tiers are small.')
]);
